org: staffinc
app: fnb-fund
service: ${self:custom.serviceName}
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: 'ap-southeast-1'
  stage: ${opt:stage, 'development'}
  memorySize: 128
  timeout: 28
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - dynamodb:*
          Resource: '*'
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: true
  environment:
    ENV: ${env:ENV}
    SERVICE_NAME: ${env:SERVICE_NAME}
    ENDPOINT_URL: ${env:ENDPOINT_URL}
    WISE_API_KEY: ${env:WISE_API_KEY}
    WISE_PROFILE_ID: ${env:WISE_PROFILE_ID}
    WISE_BALANCE_ID: ${env:WISE_BALANCE_ID}
    WISE_TRANSACTIONS_TABLE: ${env:WISE_TRANSACTIONS_TABLE}
functions:
  healthCheck:
    handler: src/handlers/health.healthHandler
    events:
      - http:
          path: health
          method: get

  wiseBalance:
    handler: src/handlers/wise.wiseBalanceHandler
    events:
      - http:
          path: wise/balance
          method: get

  wiseWebhook:
    handler: src/handlers/wise.wiseWebhookHandler
    events:
      - http:
          path: wise/webhook
          method: post

  wiseStatement:
    handler: src/handlers/wise.wiseStatementHandler
    events:
      - http:
          path: wise/statement
          method: get

  wiseStatementUpdate:
    handler: src/handlers/wise.wiseStatementUpdateHandler
    events:
      - http:
          path: wise/statement
          method: patch

  wiseStatementRefresh:
    handler: src/handlers/wise.wiseStatementRefreshHandler
    events:
      - http:
          path: wise/statement/refresh
          method: post

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  serviceName: ${env:SERVICE_NAME}
  wiseTransactionsTable: ${self:custom.serviceName}-wise-transactions
  customDomain:
    domainName: ${env:ENDPOINT_URL}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

resources:
  Resources:
    WiseTransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:WISE_TRANSACTIONS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: referenceNumber
            AttributeType: S
          - AttributeName: type
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: referenceNumber
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: type-date-index
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
